import type { Metadata } from "next";
import styles from "./layout.module.css";
import CarouselComponent from "@/components/carousel/carousel";
import { CarouselComponentProps } from "@/components/carousel/carousel";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const slides: CarouselComponentProps[] = [
    {
      heading: "Welcome to Vaibhav's Art Gallery",
      subHeading: "Explore a World of Imagination and Creativity",
      image: "https://picsum.photos/800/400",
    },
    {
      heading: "Welcome to Vaibhav's Art Gallery",
      subHeading: "Explore a World of Imagination and Creativity",
      image: "https://picsum.photos/800/400",
    },
    {
      heading: "Discover Unique Artworks",
      subHeading: "Where Every Brushstroke Tells a Story",
      image: "https://picsum.photos/800/400",
    },
    {
      heading: "Bringing Dreams to Life",
      subHeading: "Shop Original Art that Resonates with Your Soul",
      image: "https://picsum.photos/800/400",
    },
    {
      heading: "Bringing Dreams to Life",
      subHeading: "Shop Original Art that Resonates with Your Soul",
      image: "https://picsum.photos/800/400",
    },
  ];
  return (
    <html lang="en">
      <body>
        <div className={styles.authPage}>
          <div className={styles.logo}>Logo</div>
          <div className={styles.authLeft}>
            <CarouselComponent slides={slides} />
          </div>
          <div className={styles.authRight}></div>
        </div>
      </body>
    </html>
  );
}
